---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: start-renovate-openai-secret
  namespace: default
spec:
  encryptedData:
    openai.api-key: AgDQHQxFjA/j/PtnShd/T05whfqE47tj17bq81tvt/5uGGxt5TseTNP4DwqS1exOMJcWDsH7JxSQjCS4ulMtUYs5Eo95uSMayQd37+6liea9R5/OmOwnjsGGlkNPodwIb+5okynnbN22e0B/SPZJdb1nwJ5occ4x731dUmEQTUX5lAmKpHjhHpw71VxdK6x6kFNZ3PJwHXVD1rjMabSIYS4uE1QLFc4dezp1bPB0kdhWwcusQDglzf7x68KYOw7TKJYkPXR+UQrDLY/o79eXClFdi0ty9MnmLRnXjEn8h1Vei+xSKxWMih0pqo/jFp2GV7GTZqlzr9m0cYsApCZhsHkvzY2OBVhLVsx/T53Oc1b3/DNoiQwZNz3rDaHnmp3BRd6L5xa1g7J6N3j7MrBDg/z/xVbKW85SrWKKpWLSLTwr/RUu5T913tuRRqMBfGViascjFEai9mAiKhAEmOXBRqe4GLK1R8VyQ292ESFao4YVxouGJVoByctveWTD4uZ7Syu2Fa3CTMIdHctfiTMsQMN8vitUYiJPi7UaWqPFkfNQzdSDZa3lcdF53A+Dix1mQ4nHrJ2+fF1egxTj8DUzLST+BcGQDKuUgq4Wm/HoD9q4+vTaTrWM8d3JHHyg+RAdQYFiyANOYg4PFZMu1hhjdq6af3HY84lEXq6L6goTx5YatI0u/vBOWK7nyYBANjUEzzyMs6Lt3bzAu1DZB2Sm5Q+4xHNsewrXapza2D9er4W08S9KfwIRcMXkIH1De67LFhDo1d70P0rqburJsHGKctSetrVvyjTOdM3LGpXwNV9RsxqJCIaS7/Hm6OfdoSL6RqyBO3CyuZMw45aNwG2B6nt7xR0FbiH8ktlsEJAkXN8S8AC1xQf42hdfPE+Sp8fk20znCTKvFnivp7tWAGZ0DZpKzJaGvw==
  template:
    metadata:
      name: start-renovate-openai-secret
      namespace: default
    type: Opaque
